apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: MONGO_URI
          value: {{ .Values.env.MONGO_URI | quote }}
        - name: MONGO_USERNAME
          value: {{ .Values.env.MONGO_USERNAME | quote }}
        - name: MONGO_PASSWORD
          value: {{ .Values.env.MONGO_PASSWORD | quote }}

        ports:
        - containerPort: {{ .Values.service.targetPort }}
