name: CI - Docker

on:
  workflow_call:
    inputs:
      test-result:
        required: true
        type: string
      coverage-result:
        required: true
        type: string
    outputs:
      image-tag:
        description: "Docker image tag"
        value: ${{ jobs.docker.outputs.image }}

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
        MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
        MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
        MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
    outputs:
      image: ${{ steps.meta.outputs.tag }}
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - id: meta
        run: echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT

      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
